### ISSUE TITLE
new PoGo API

### ISSUE THREAD

**Issue by umutafacan** [earshel/PokeyPySnipe#19] opened 2016-08-05 06:45 UTC
as i tried, at least snipe function is not working, so only going not finding any pokemon. new api's looks like ready, will be there any implement for that? 
ps: Thanks for your great work.

**Comment by earshel** [comment] 2016-08-07 20:05
Updated it, check it out. Let me know if it doesn't work ;)

**Comment by kriswong** [comment] 2016-08-07 22:00
I keep on getting failed to build xxhash when doing the "pip install -r requriements.txt".

Failed with Error Code 1.

**Comment by kriswong** [comment] 2016-08-07 22:03
Never mind... you need to install this file and it will compile correctly http://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by earshel** [comment] 2016-08-07 22:15
Oh, thanks for letting me know that...I already have all of that stuff installed, so I never ran in to that issue. I'll update the instructions.

**Comment by kriswong** [comment] 2016-08-07 22:38
No problem.

There is still an issue throwing errors when launching the Launch.bat.

Traceback (most recent call last):
  File "C:\Users\XXX\Desktop\PokeyPySnipe-master\pogo\snipe.py", line 458, in
<module>
    minCP = int(config.get('CONFIG','minCP'))
  File "C:\Python27\lib\ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'CONFIG'

I double Check and the Config.ini contains a minCP value... so not sure what is going on but it is not being read correctly.  Here is my config.ini file 
"[AUTH]type = google
username = XXXXXX.XXXXX.XXXXX@gmil.compassword = XXXXXXX[CONFIG]startLoc = XXXXminCP = 0"

**Comment by earshel** [comment] 2016-08-07 22:46
Perhaps the startLoc is not formatted correctly, causing minCP to not be read? How are your starting coords formatted? Is there a line break after startLoc? Should be like: 
[AUTH]
type = google
username = user@gmail.com
password = password

[CONFIG]
startLoc = Central Park NY
minCP = 0

**Comment by stumpyb** [comment] 2016-08-07 22:51
@earshel am i able to use this on linux still or is it only able to load .dll libraries rather than .so as well?

edit: it works! thanks for the update man!

**Comment by earshel** [comment] 2016-08-07 23:00
@stumpyb nice! Glad to hear it works for you. I just added the libencrypt.so files in to the repo for you ;P. The Pokemon Inventory page is a little experimental at the moment. Mostly useful for transferring in bulk. If you happen to test it out, please let me know if you encounter any errors. Cheers!

**Comment by kriswong** [comment] 2016-08-07 23:07
@earshel still no go on windows. There was something misformatted but now its Error 126. The specified module could not be found... 
File "C:\Users\XXX\Desktop\PokeyPySnipe-master\pogo\util.py", line hashSignature
    library = ctypes.cdll.LoadLibrary(libraryPath)
File "C:\Python27\lib\ctypes__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
File "C:\Python27\lib\ctypes__init__.py", line 362, in **init**
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

**Comment by earshel** [comment] 2016-08-07 23:09
@kriswong For some reason encrypt.dll did not make it in to the repo. I just committed it. It's in the /pogo/ directory. Download it and place it in the /pogo/ directory and try running it again. It should fix the problem.

**Comment by stumpyb** [comment] 2016-08-07 23:13
it depends on your architecture (32 or 64 bit) as well. some available here: https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/pogom

**Comment by kriswong** [comment] 2016-08-07 23:25
@earshel cool beans. WebServer now loads. Now the issue is that no pokemon are found when providing the snipe coordinates... I know they are good as I GPS spoof using xcode and they show up... weird eh.

**Comment by earshel** [comment] 2016-08-07 23:28
@kriswong Are you providing the coordinates in the proper format? it must be ###.#####,###.#####
Try clicking the coordinates for the top Pokemon on this site: http://www.pokespawns.be/ and pasting them. I know these coordinates are formatted correctly and are usually up to date.

**Comment by kriswong** [comment] 2016-08-07 23:32
Yeah I tried those which is where I was GPS spoofing from. doesn't seem to work.
"Status: Did not find any pokemon @ given location. Redirecting in 5 seconds"
Every time even tho I know that it a valid pokemon....

**Comment by kriswong** [comment] 2016-08-07 23:40
@earshel I think it is beacuse they changed the scan delay to 10s rather than 5s. I changed the delay in the snipe.py to 15s and it works now.,..

**Comment by earshel** [comment] 2016-08-07 23:43
@kriswong Yeah, that's it. I figured it out at the same time and tested it. Changing it to 10 seconds and putting it before getMapObjects works a charm. I committed a new snipe.py that should be more efficient than the old one with your change to 15 sec delay.

**Comment by kriswong** [comment] 2016-08-07 23:45
@earshel Cool. That is awesome thanks for that!. I'll reload and test again. :) looks like at 15s it works but cycles through the throttling check once before finding the intended pokemon. Ill let you know how it goes on the new snipe.py file

**Comment by kriswong** [comment] 2016-08-07 23:50
Bah softban.

**Comment by kriswong** [comment] 2016-08-07 23:55
@earshel is there anyway for you to display the IV or the Attack/Def/Stamina on the Pokemanager?

**Comment by earshel** [comment] 2016-08-07 23:56
@kriswong Yeah, I had that initial throttling check at the wrong place in the code, so it would always waste the first check.

It was set up like this:

> Move to snipe location
> Search for Pokemon
> Wait 10 sec for throttling check
> Search for Pokemon again

Now it acts like this

> Move to snipe location
> Wait 10 sec for throttling 
> Search for pokemon
> Engage

**Comment by earshel** [comment] 2016-08-08 00:11
@kriswong  I just committed a new /pogo/templates/inventory.html that includes the 3 IV values on the management page

**Comment by deblackfisk** [comment] 2016-08-08 06:18
@earshel im facing an error related to AUTH process.

ImportError : No module named configparser

checked to installed dir python location, the file is exist

**Comment by earshel** [comment] 2016-08-08 12:37
@deblackfisk Are you using Python 2.7.2? I've seen this issue arise if you try to use Python 3.

**Comment by earshel** [comment] 2016-08-08 13:12
Closing this issue because there's so many different comments here. @deblackfisk if you are still having an issue please open a fresh issue. Thank you.

**Closed as completed by earshel** 2016-08-08 13:12 UTC
